-- Autogenerated by Luapress v3.3
-- For available configuation options, see: fizzadar.com/luapress
-- Or see the default config at:
-- github.com/Fizzadar/Luapress/blob/develop/luapress/default_config.lua

local config = {
    url = 'http://apoio.partidopirata.xyz',

    title = 'Coleta de assinaturas',

    index_page = 'home',
}

return config
