# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20160515_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
    ]
