# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(max_length=300)),
                ('collector_type', models.CharField(choices=[('BO', 'Comitê de Coleta'), ('PO', 'Ponto de Coleta')], default='PO', max_length=2)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman_name', models.TextField()),
                ('street_name', models.TextField()),
                ('street_cep', models.PositiveIntegerField(default=0)),
                ('region_place', models.CharField(max_length=300)),
                ('city_name', models.TextField()),
                ('estate_name', models.TextField()),
                ('telefone_number', models.PositiveIntegerField(default=0)),
                ('website_address', models.CharField(max_length=300)),
                ('email_address', models.CharField(max_length=300)),
                ('coordinates', models.CharField(max_length=300)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coletores.Collector')),
            ],
        ),
    ]
